### ISSUE TITLE
FR: Color output

### ISSUE THREAD

**Issue by krlmlr** [kwstat/lucid#2]
Instead of discarding insignificant digits, they could be shown in pale gray. In cases like 1.2473 and 3 digits, perhaps the 7 can be displayed in a darker gray.

For hadley/tibble#30. The crayon package could take care of coloring the output.

**Comment by kwstat** [comment]
It's a nice idea.  Supporting this for all output styles (TeX, Word, html) needs would need a fairly massive change in architecture.
