### ISSUE TITLE
FR: Use exponential notation if it saves space

### ISSUE THREAD

**Issue by krlmlr** [kwstat/lucid#3]
Example:

```r
lucid::lucid(c(1e-6, 1e-5))
## [1] " 1e-6" "10e-6"
```

Perhaps only multiples of 3 need to be allowed as exponent, e+3 and e-3 would never be used.

**Comment by kwstat** [comment]
There may be an opportunity to consider this at some point, but for now one of the design goals of lucid is to remove exponential notation as much as possible in order to make it easier to read by humans.
